### ISSUE TITLE
I have got a question about dilate>2 problem of conv layer in Mxnet

### ISSUE THREAD

**Issue by ascust** [kadeng/tutorials#1]
Sorry I did not know how to contact you, so I just left a message here. 
I recently found the problem of dilate >2 problem in Mxnet's conv layer and I found your post. It seems good but I have got a problem. Since cudnn version of convolution layer has no dilate involved. Is that possible to implemented cud version as well?
Best regards,

**Comment by kadeng** [comment]
Hi,

as far as I know, CuDNN doesn't have direct support for dilate, so probably no. It should be possible to force the usage of the non-CuDNN version of Convolution somehow, though, even if you are otherwise using CuDNN for everything else...

**Comment by kadeng** [comment]
See my last comment in https://github.com/dmlc/mxnet/issues/1645

**Comment by ascust** [comment]
Thanks man.
